runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /.*
  script: webproxy.app

libraries:
- name: webapp2
  version: latest
  